### ISSUE TITLE
Visitor log actions icons alignment

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12770]
Minor feedback: in Visitor Log, some icons are not vertically aligned.
In this example you can see that while the Conversion icon is middle aligned, the Content Tracking icons are not (they are slightly too high). 

## Example 1: content interaction too high

![content tracking](https://user-images.githubusercontent.com/466765/39297698-4a6e7d4e-4998-11e8-9ab5-953f274c062b.png)

## Example 2: content impression too high
![sne](https://user-images.githubusercontent.com/466765/39415367-70a35e84-4c96-11e8-9dd1-59b7c3b04ba8.png)

## Example 3: outlinks too low

![too low](https://user-images.githubusercontent.com/466765/39415377-9ebd045a-4c96-11e8-9f8b-8d32bf8651a0.png)

**Comment by fdellwing** [comment]
Should be possible with CSS.

plugins/Live/stylesheets/live.less - Line 295ff
```css
.action-list-action-icon {
    display: inline;
    margin: 2px 3px 0 0;
    max-height: 16px;
 
    &.outlink {
      margin: 7px 3px 0 0;
    }
}
```
