### ISSUE TITLE
hosting matomo in subdirectory

### ISSUE THREAD

**Issue by courtens** [matomo-org/matomo#13627]
I reported this problem some time ago in the forum under "[Bug? Proxy redirect to root after login success - instead of staying within assigned sub-folder](https://forum.matomo.org/t/akismet-has-temporarily-hidden-your-post/19925?u=courtens)". If I remember right the problem started about 3 years ago with one of the mayor updates.

The problem is that I can not host the code from within a sub-folder of a website without some functions not working. Some of the problems: 1) During login I get redirected to the root folder. 2) "[All Websites](index.php?module=MultiSites&action=index&idSite=1&period=range&date=previous30)" `index.php?module=MultiSites&action=index&idSite=1&period=range&date=previous30` produces a page with no record content showing.

**Comment by micw** [comment]
If you run it behind a proxy, you can configure it this way: https://matomo.org/faq/how-to-install/faq_98/
But IMO this should be an application setting and should not rely on special proxy settings.

**Comment by heikojansen** [comment]
I don't know if 1) is related to the MultiSites plugin but 2) certainly is:

I see data in the "All Websites" page but the sparkline graphics do not show up.
I think this is because here:
https://github.com/matomo-org/matomo/blob/19377972454bfe3c4cdc7778e144cb6107b4af44/plugins/MultiSites/angularjs/site/site.controller.js#L44
the URL used for the sparkline generation is absolute in relation to the installation and thus not working when used behind a reverse proxy and in a different subdirectory.

This can be fixed by simply removing the "piwik.piwik_url" part from the returned URL.

Just make sure to run "php ./console cache:clear" to see any effect.

**Comment by christw92** [comment]
@micw Are you talking about adding the `X-Forwarded-Uri` Header for the proxying webserver and setting the `proxy_uri_header = 1` inside `config/config.ini.php` ? I tried that but I still get 302 redirects to `/`

> If you run it behind a proxy, you can configure it this way: https://matomo.org/faq/how-to-install/faq_98/
> But IMO this should be an application setting and should not rely on special proxy settings.

**Comment by micw** [comment]
Can't remember (was 1,5 years ago) and I don't use it anymore.

**Comment by d2a-raudenaerde** [comment]
@heikojansen  The MultiSites is broken I think, see  : https://forum.matomo.org/t/4-4-1-reverse-proxy-links-to-websites-on-dashboard-dont-work-properly/42978
Did you have any success running it?

**Comment by papadave66** [comment]
i have the same problem. i am running Matomo 5.2.2 in docker.
docker yml file:
```
matomo:
        image: matomo:latest
        restart: always
        volumes:
#     - ./config:/var/www/html/config:z
#     - ./logs:/var/www/html/logs:z
         - matomo:/var/www/html:z
        environment:
         - MATOMO_DATABASE_HOST=mysql
         - PHP_MEMORY_LIMIT=1G
        env_file:
         - ./db.env
        ports:
         - 8080:80
        deploy:
            resources:
                reservations:
                    memory: 1.5G
                limits:
                    memory: 2G
```
config.ini.php
```
[General]
proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"
salt = "bc2962ef4123e9b8cb978d7920cab725"
trusted_hosts[] = "10.151.xx.xx"
enable_form_security = 0
;assume_secure_protocol = 1
proxy_ip_read_last_in_list = 0
```
nginx.conf
```
    # Proxy for matomo
    location /matomo {
        proxy_pass http://localhost:8080;
        rewrite ^/matomo/(.*)$ /$1 break;
        proxy_set_header X-Forwarded-Uri /matomo;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
#       proxy_redirect / /matomo;
    }
```

if i visit 10.151.xx.xx/matomo/ the login page shows. and when i login, it redirect to / instead of /matomo/
```
10.1.xxx.13 - - [12/Mar/2025:08:21:22 +0800] "POST /matomo/index.php?module=Login HTTP/1.1" 302 0 "http://10.151.xx.xx/matomo/index.php?module=Login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
10.1.xxx.13 - - [12/Mar/2025:08:21:22 +0800] "GET /index.php HTTP/1.1" 404 1174 "http://10.151.xx.xx/matomo/index.php?module=Login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
```
It happens at the first time login. if i enter /matomo/ manually after login . then exit the login session and login again. it will enter the right sub path /matomo/
